version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: order-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: springuser
      MONGO_INITDB_ROOT_PASSWORD: 29AZSaQR9DJSxenw
      MONGO_INITDB_DATABASE: chickfish
    volumes:
      - ./data/mongodb:/data/db